# Generated by Django 4.1.1 on 2022-09-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
