# Generated by Django 4.1 on 2022-09-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_mytodo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodo',
            old_name='status',
            new_name='complete',
        ),
    ]
